GET http://localhost:8000/

###################################################### Services

### 

GET http://localhost:8000/services/

###

GET http://localhost:8000/services/1

####################################

POST http://localhost:8000/services/
content-type: application/json

{
    "name": "Service1",
    "description": "Nice Service",
    "logo": "logo.png",
    "link": "app.io"
}

###

PUT http://localhost:8000/services/
content-type: application/json

{
    "id": 1,
    # "name": "Service UPDATE c:",
    # "description": "Super Duper Cool Service",
    # "logo": "123path123",
    # "link": "path5",
    "visibility": "true"
}

###

DELETE http://localhost:8000/services/1