GET http://localhost:8000/

###################################################### Services

### 

GET http://localhost:8000/services/

###

GET http://localhost:8000/services/25

####################################

POST http://localhost:8000/services/
content-type: application/json

{
    "name": "Service4",
    "description": "Nice Service",
    "logo": "logo.png",
    "link": "app4.io"
}

###
# ISSUE -> If not all atributes are given, it fails

PUT http://localhost:8000/services/
content-type: application/json

{
    "id": 25,
    "name": "Service UPDATE",
    "description": "Super Duper Cool Service",
    "logo": "123path123.ab",
    "link": "path5.sq",
    "is_visible": "false",
    "bla":"foo"
}

###

DELETE http://localhost:8000/services/1