"""remove a column for testing migrations

Revision ID: dde3dfa79c4a
Revises: e51124102a7a
Create Date: 2022-04-18 19:16:13.788669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde3dfa79c4a'
down_revision = 'e51124102a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'test_mig')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'services',
        sa.Column(
            'test_mig',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True
            )
        )
    # ### end Alembic commands ###
