[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.mypy]
python_version = 3.9
ignore_missing_imports = true
disallow_untyped_defs = true
exclude = "src/hub/alembic"