GET http://localhost:8000/

###################################################### Services

### 

GET http://localhost:8000/services/

###

GET http://localhost:8000/services/20

####################################

POST http://localhost:8000/services/
content-type: application/json

{
    "name": "Service BRAND NEW",
    "description": "Nice Service",
    "logo": "logo.png",
    "link": "app4.io"
}

###
PUT http://localhost:8000/services/
content-type: application/json

{
    "id": 30,
    "name": "Updated Servicex2 id30 :)",
    "foo": "bar"
}

###

DELETE http://localhost:8000/services/25