"""Added column test_mig to Service table

Revision ID: 16518e96afe1
Revises: 7dae0f94240b
Create Date: 2022-04-18 17:05:44.159520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16518e96afe1'
down_revision = '7dae0f94240b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
